// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLViecLam.Data;

#nullable disable

namespace QLViecLam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240119081605_Add-DanhMuc")]
    partial class AddDanhMuc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmChucVu");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmDoiTuongUuTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmDt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDoiTuongUuTien");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmHinhThucLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiHieuLucHdld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLhl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHieuLucHdld");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiHinhHdkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDmLhkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHinhHdkt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmMangHeTrinhDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmmNtd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDmmNtd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmMangHeTrinhDo");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNganhNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhNghe");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNganhSxkd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmSxkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenSxkd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhSxkd");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNgheCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNgheCongViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNguyenNhanThatNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNguyenNhanThatNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdkt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdktCt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgktCt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgktCt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdktCt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdktCt2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgktCt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhom2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgktCt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdktCt2");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTrinhDoGdpt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmGdpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGdpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoGdpt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTrinhDoKyThuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("Tentdkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoKyThuat");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DmDonvi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapHanhChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvcq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDvHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDonvi");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DmHanhChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Public")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHanhChinh");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsNhomTaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenNhomChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsNhomTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteRecordTrash")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChucDanhNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChucNangKhac")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountLogin")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaDanhBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeThong")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Public")
                        .HasColumnType("int");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuanBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TongHop")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
