// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLViecLam.Data;

#nullable disable

namespace QLViecLam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240717051428_up-all-int")]
    partial class upallint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.BanTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiDiem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BanTin");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.BienDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiDiem")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BienDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.CheDoChinhSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Bhtn")
                        .HasColumnType("float");

                    b.Property<double?>("Bhxh")
                        .HasColumnType("float");

                    b.Property<double?>("Bhyt")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HuuTri_Nld")
                        .HasColumnType("float");

                    b.Property<double?>("HuuTri_Nsdld")
                        .HasColumnType("float");

                    b.Property<string>("MaBhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OmDau_Nld")
                        .HasColumnType("float");

                    b.Property<double?>("OmDau_Nsdld")
                        .HasColumnType("float");

                    b.Property<string>("SoTienDaDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTienDaHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThaiSan_Nld")
                        .HasColumnType("float");

                    b.Property<double?>("ThaiSan_Nsdld")
                        .HasColumnType("float");

                    b.Property<double?>("Tnld_Nld")
                        .HasColumnType("float");

                    b.Property<double?>("Tnld_Nsdld")
                        .HasColumnType("float");

                    b.Property<double?>("TuTuat_Nld")
                        .HasColumnType("float");

                    b.Property<double?>("TuTuat_Nsdld")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CheDoChinhSach");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuCn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhuVuc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Public")
                        .HasColumnType("int");

                    b.Property<string>("QuyMo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sld")
                        .HasColumnType("int");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhTrangXacThuc")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DieuKienLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DieuKienLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DsThatNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoCmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DsThatNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.KeHoachThuThapThongTin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucDanhKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTenNguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeHoach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeHoachThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoiLuongThongTinThuThap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinhPhiThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoTraLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKeHoach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKyKeHoach")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapKeHoach")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenTacThuThap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungThuThap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamThuThap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoKeHoach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToChucThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeHoachThuThapThongTin");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.KyBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cqtiepnhan_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cqtiepnhan_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lydo_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lydo_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KyBaoCao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.KyDieuTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KyDieuTra");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.NguoiLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abroad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BdBhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BdDocHai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BdHopDong")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiCuThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("FromTtdvvl")
                        .HasColumnType("smallint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KtBhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KtDocHai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KtHopDong")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinhVucDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuongBhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThangNamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcThamNien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcThamNienNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBaoHiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoCMKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.NhanKhau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongViecCuThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DanhSach_id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiNoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuongTimViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoaiBienDong")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoKhongThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBHXH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNgheMongMuon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNgheMuonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThangNamSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiOHienTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuongBienDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDinhDanhHoGD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTrung")
                        .HasColumnType("int");

                    b.Property<string>("ThamGiaBHXH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThiTruongLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianThatNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhTrangXacThuc")
                        .HasColumnType("bit");

                    b.Property<string>("TrinhDoCMKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoChuyenMonMuonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.Property<string>("UuTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViecLamMongMuon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanKhau");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.PhuongTienLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhuongTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PhuongTienLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.RuiRoLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaRuiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenRuiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RuiRoLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.TaiNanLaoDong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ccnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNguoiLaoDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaRuiro")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TaiNanLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.TongHopCungLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("HocNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdKhongThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdThatNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdTren15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdcoViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NongThon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuocNgoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrongNuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TongHopCungLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.TuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucvuTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<short?>("DaTuyen")
                        .HasColumnType("smallint");

                    b.Property<short?>("DaTuyenTutt")
                        .HasColumnType("smallint");

                    b.Property<string>("EmailTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("State")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TuyenDung");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ViTriTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("BacNghe")
                        .HasColumnType("smallint");

                    b.Property<string>("CapBac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChungChiNn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChungChiNn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungTay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungVaDiLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuclv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTroAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTuyenDung")
                        .HasColumnType("int");

                    b.Property<string>("KyNangMem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThvp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichLv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhucLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Soluong")
                        .HasColumnType("smallint");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tdcmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tdgd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTacTay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThiLuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinHocKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrongLuongNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("UuTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeploaiNn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeploaiNn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCauKn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCautThem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViTriTuyenDung");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DanToc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanToc");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmChucVu");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmDoiTuongChinhSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDoiTuongChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoiTuongChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDoiTuongChinhSach");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmDoiTuongUuTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmDt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDoiTuongUuTien");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmHinhThucDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHinhThucDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHinhThucDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucDaoTao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmHinhThucDoanhNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHinhThucDoanhNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHinhThucDoanhNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucDoanhNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmHinhThucLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmHinhThucThamGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHinhThucThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHinhThucThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucThamGia");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmKhuCongNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhuCongNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmKhuCongNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmLoaiHieuLucHdld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLhl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHieuLucHdld");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmLoaiHinhDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLoaiHinhDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiHinhDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHinhDaoTao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmLoaiHinhHdkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDmLhkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHinhHdkt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmLoaiLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmLoaiViecLam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLoaiViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiViecLam");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmMangHeTrinhDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmmNtd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDmmNtd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmMangHeTrinhDo");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNganhNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhNghe");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNganhSxkd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmSxkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenSxkd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhSxkd");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNgheCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNgheCongViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNgheDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNgheDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNgheDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNgheDaoTao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNguonViecLam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNguonViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguonViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNguonViecLam");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmNguyenNhanThatNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNguyenNhanThatNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmThoiGianLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaThoiGianLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThoiGianLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmThoiGianLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmTinhTrangTanTat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTinhTrangTanTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhTrangTanTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangTanTat");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmTonGiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTonGiao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmTrangThaiViecLam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTrangThaiViecLam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThaiViecLam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrangThaiViecLam");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmTrinhDoNgoaiNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTrinhDoNgoaiNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDoNgoaiNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoNgoaiNgu");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmTrinhDoTinHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTrinhDoTinHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDoTinHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoTinHoc");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.DmXuatKhauLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaXuatKhauLaoDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXuatKhauLaoDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmXuatKhauLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.NganhHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNganhHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganhHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NganhHoc");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.QuocGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaQuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("QuocGia");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.TinhTrangVL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTinhTrangVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhTrangVL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TinhTrangVL");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.TrinhDoCMKT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTrinhDoCMKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDoCMKT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrinhDoCMKT");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DanhMuc.TrinhDoHV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTrinhDoHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDoHV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrinhDoHV");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.ChucNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapDo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChucNang");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DmDonvi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDvHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDonvi");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DmHanhChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHanhChinh");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DsNhomTaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DsNhomTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteRecordTrash")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DsTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.DvDieuTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Huyen")
                        .HasColumnType("int");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoiLoai1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoiLoai2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoiLoai3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoHo")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("Tinh")
                        .HasColumnType("int");

                    b.Property<int?>("Xa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DvDieuTra");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.HeThongChung.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChucDanhNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChucNangKhac")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountLogin")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaDanhBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeThong")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Public")
                        .HasColumnType("int");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuanBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TongHop")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
