// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLViecLam.Data;

#nullable disable

namespace QLViecLam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240119093829_update-System1")]
    partial class updateSystem1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmChucVu");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmDoiTuongUuTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmDt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDoiTuongUuTien");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmHinhThucLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHinhThucLamViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiHieuLucHdld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLhl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHieuLucHdld");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiHinhHdkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDmLhkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLhkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHinhHdkt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmLoaiLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmLld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenLld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmMangHeTrinhDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmmNtd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDmmNtd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmMangHeTrinhDo");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNganhNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhNghe");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNganhSxkd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmSxkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenSxkd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNganhSxkd");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNgheCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNgheCongViec");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmNguyenNhanThatNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmNguyenNhanThatNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdkt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdktCt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgktCt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgktCt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdktCt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTinhTrangThamGiaHdktCt2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTgktCt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhom2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenTgktCt2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTinhTrangThamGiaHdktCt2");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTrinhDoGdpt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmGdpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGdpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoGdpt");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.DanhMuc.DmTrinhDoKyThuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDmTdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("Tentdkt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoKyThuat");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dkkd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuCn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhuVuc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Public")
                        .HasColumnType("int");

                    b.Property<string>("QuyMo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sld")
                        .HasColumnType("int");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("User")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.DsThatNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoCmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DsThatNghiep");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.KyBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cqtiepnhan_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cqtiepnhan_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lydo_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lydo_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Madv_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoidiem_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_t")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai_x")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KyBaoCao");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.NguoiLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BdBhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BdDocHai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BdHopDong")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ccnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("FromTtdvvl")
                        .HasColumnType("smallint");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KtBhxh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KtDocHai")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KtHopDong")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinhVucDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Luong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuongBhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcThamNien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcThamNienNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBaoHiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoCmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoGiaoDuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.NhanKhau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenMonKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongViecCuThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DanhSach_id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoiTuongTimViecLam")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hdld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhongThamGiaHdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhuVuc")
                        .HasColumnType("int");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoaiBienDong")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHinhNoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mqh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNgheMongMuon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhNgheMuonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiCoVieclam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuongBienDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTrung")
                        .HasColumnType("int");

                    b.Property<string>("ThamGiaBhxh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThatNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThiTruongLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianThatNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangHdkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoChuyenMonMuonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoGiaoDuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("UuTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViecLamMongMuon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhanKhau");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.TongHopCungLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("HocNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyDieuTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdKhongThamGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdThatNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdTren15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdcoViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NongThon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NuocNgoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrongNuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TongHopCungLaoDong");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.TuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucvuTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<short?>("DaTuyen")
                        .HasColumnType("smallint");

                    b.Property<short?>("DaTuyenTutt")
                        .HasColumnType("smallint");

                    b.Property<string>("EmailTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneTd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("State")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.Property<string>("YeuCau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TuyenDung");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Manages.ThongTinThiTruongLD.ViTriTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("BacNghe")
                        .HasColumnType("smallint");

                    b.Property<string>("CapBac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChungChiNn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChungChiNn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungTay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungVaDiLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuclv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTroAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTuyenDung")
                        .HasColumnType("int");

                    b.Property<string>("KyNangMem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThvp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichLv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhucLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Soluong")
                        .HasColumnType("smallint");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tdcmkt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tdgd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTacTay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThiLuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinHocKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrongLuongNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("UuTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeploaiNn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XeploaiNn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCauKn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YeuCautThem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViTriTuyenDung");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DmDonvi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapHanhChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvcq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDvHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TtLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmDonvi");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DmHanhChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Public")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DmHanhChinh");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsNhomTaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenNhomChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsNhomTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteRecordTrash")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsNhomTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.DsTaiKhoan_PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DanhSach")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoanThanh")
                        .HasColumnType("bit");

                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhanQuyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThayDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DsTaiKhoan_PhanQuyen");
                });

            modelBuilder.Entity("QLViecLam.Models.Admin.Systems.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChucDanhNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChucNangKhac")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountLogin")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaDanhBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeThong")
                        .HasColumnType("bit");

                    b.Property<string>("HoTenNguoiKyBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDvBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Public")
                        .HasColumnType("int");

                    b.Property<string>("Remember_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuanBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TongHop")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
